### ISSUE TITLE
Sudden Java Exception

### ISSUE THREAD

**Issue by GamingCoookie** [LogisimIt/Logisim#10]
I wanted to continue working on my logisim project but now neither .exe nor .jar want to open and I even tried reinstalling Java yet I get the same "Java Virtual Machine Launcher: A Java Exception has occured." error.
Do you have any idea how to fix this problem?
I can provide extra information if needed

**Comment by maehne** [comment]
Please provide some more details:

- Which exact version of Logisim-ITA are you using? If unsure, provide the download link.

- On which operating system, in which version, and on which processor platform?

- Which JDK version did you install? The last version of Logisim-ITA seems to have been tested with  JDK 10.

Additionally, do you use any Logisim-ITA-specific circuit blocks in your design?

**Comment by GamingCoookie** [comment]
I am using the latest version of Logisim-ITA, that you can get on http://logisim.altervista.org/

I am having Windows 10 Version 1903 and on EM64T (if that is what is asked)

I have Version 8 Update 231

I don't think so but it fails even opening on its own without any circuit.

**Comment by maehne** [comment]
> I have Version 8 Update 231

This Java version is definitely too old as Logisim-ITA version 2.15.0.1 was compiled against Java 10. I would suggest that you install OpenJDK 11 LTS or later, e.g., available from [AdoptOpenJDK](https://adoptopenjdk.net/releases.html).

**Comment by GamingCoookie** [comment]
Downloaded the latest OpenJDK 13 from there. It's working now again.

Thank you for the quick help!
