### ISSUE TITLE
LED Matrix Dot Shape Bug

### ISSUE THREAD

**Issue by totalcontrol** [LogisimIt/Logisim#11]
If  you set dot shape as circular， logisim will down！

**Comment by totalcontrol** [comment]
Fix the bug !!!
CommentDrawContext.java
	public void drawRoundBounds(Component comp, Bounds bds, Color color) {
		GraphicsUtil.switchToWidth(g, 2);
		if (color != null && (AppPreferences.FILL_COMPONENT_BACKGROUND.getBoolean() || !color.equals(Color.WHITE))) {

**Comment by maehne** [comment]
If you know the approximate location of the bug, try to fix it and make a PR. You may also check out for implementation differences between Logisim-ITA and [Logisim-evolution](https://github.com/reds-heig/logisim-evolution). Most, if not all, improvements / new features implemented by the people behind Logisim-ITA got in the meantime integrated into Logisim-evolution with approval by the Logisim-ITA authors. However, you will need to to build Logisim-eovlution from the [develop branch](https://github.com/reds-heig/logisim-evolution/tree/develop) to gain access to all the latest features. If you are missing functionality in Logisim-evolution, which is present in Logisim-ITA, create an issue.

**Comment by maehne** [comment]
Unfortunately, the Logisim-ITA development seems to have stalled a bit. Last commit on master branch is from November 2018 and in early branch is from January 2019.

**Comment by AndreaNeti** [comment]
Thanks, fixed!
Sorry for my inactivity but I'm really busy with the university :/
