### ISSUE TITLE
Homepage not reachable via HTTPS

### ISSUE THREAD

**Issue by maehne** [LogisimIt/Logisim#13]
The GitHub project references [`https://logisim.altervista.org/`](https://logisim.altervista.org/) as homepage. However, opening that page using HTTPS fails with an error that the browser is not able to open a secure connection to the web server. The homepage opens fine if HTTP is used: [`http://logisim.altervista.org/`](http://logisim.altervista.org/).

**Comment by AndreaNeti** [comment]
Thanks, I forgot to re-enable https after trying a change to the website :)
