### ISSUE TITLE
Suggestion: toggle display of grid

### ISSUE THREAD

**Issue by exfinium** [LogisimIt/Logisim#3]
Just responding to a request for suggestions.  Sorry I can't translate.

It's only a cosmetic niggle but I would like the option to hide the grid.  Preferably as a menu option/hotkey but even as a preference setting would be nice.

**Comment by AndreaNeti** [comment]
It already exists, It's the little button at the right of the zoom bar
(lower-left corner), maybe i can try changing the icon to make it more easy
to understand

Il 25 Feb 2018 00:00, "matmanj" <notifications@github.com> ha scritto:
