### ISSUE TITLE
Issue Editing ROM Data

### ISSUE THREAD

**Issue by StuartP119** [LogisimIt/Logisim#5]
I just installed the 2.15.0.0 exe version and when you view data bytes in the Window of the "chip" the information is displayed and works correctly. The problem is when you right click and select "edit contents" the first column appears to delete leading zero's. For example if you have a 16 bit word and put in 000A it will display as A000. When you look at the same contents via the Window on the chip from a circuit it will display and function properly as 000A

Note this issues appears to only happen with the first column. All other columns appear to display properly. 

Thank you for your work and looking at this minor issue
-Stuart

**Comment by AndreaNeti** [comment]
Thanks, I'll take a look

Il Mer 9 Mag 2018, 14:59 StuartP119 <notifications@github.com> ha scritto:
