### ISSUE TITLE
3 input XOR Bug

### ISSUE THREAD

**Issue by suphadej** [LogisimIt/Logisim#8]
A XOR B XOR C' not equal (A XOR B) XOR C'    When A = 1 B =1 and C = 0
C' = NOT C
![XOR Bug](https://user-images.githubusercontent.com/52889453/61186219-f48ca100-a68c-11e9-91ff-e9c0141e6621.PNG)

**Comment by maehne** [comment]
The multiple-input behaviour of the XOR gate can be configured in its properties. It can be either "When one input is on" or "When an odd number of bits is on". Default is "When one input is on". So, the behaviour, which you are observing is expected. For details, check out the XOR gate documentation in Logisim's Library Reference, which you can access through the Help menu.
