### ISSUE TITLE
Programmable generator.  I cannot enter zero value as initial data

### ISSUE THREAD

**Issue by ArielG100** [LogisimIt/Logisim#9]
When I try to send a low signal as the first signal of my generator, In the high signal column I place the value zero but it does not accept it and forces me to send high signals at the beginning of the transmission

**Comment by AndreaNeti** [comment]
Didn't thought about the necessity to start with low state, fix will come in next update

**Comment by maehne** [comment]
Thanks @LogisimIt for fixing the issue! I have referenced your fix in the respective [Logisim-evolution issue #277](https://github.com/reds-heig/logisim-evolution/issues/277), so that it can be fixed there, too.
